name: Progress report

on:
  workflow_dispatch:
  schedule:
    - cron: "17 3 * * 1"

permissions:
  contents: read
  pull-requests: read

jobs:
  report:
    name: Course progress
    uses: web-programming-contest/web-programming-ci-utils/.github/workflows/progress-report.yml@f16318b41c989c814ec3059f0da96753b64a22f7
    with:
      utils_repository: web-programming-contest/web-programming-ci-utils
      utils_ref: "f16318b41c989c814ec3059f0da96753b64a22f7"
