name: Progress report

on:
  workflow_dispatch:
  schedule:
    - cron: "17 3 * * 1"

permissions:
  contents: read
  pull-requests: read

jobs:
  report:
    name: Course progress
    uses: web-programming-contest/web-programming-ci-utils/.github/workflows/progress-report.yml@df2e4096a7f45dd0a3598978a7c6b25aae9b6599
    with:
      utils_repository: web-programming-contest/web-programming-ci-utils
      utils_ref: "df2e4096a7f45dd0a3598978a7c6b25aae9b6599"
