name: Submission

on:
  pull_request:
    branches: [master]
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: read
  pull-requests: read

jobs:
  submission:
    name: Automated submission checks
    uses: web-programming-contest/web-programming-ci-utils/.github/workflows/submission.yml@81a6b74d5eae66c04c0d2e6fa3fc05799c0f4364
    with:
      utils_repository: web-programming-contest/web-programming-ci-utils
      utils_ref: "81a6b74d5eae66c04c0d2e6fa3fc05799c0f4364"
