name: Submission

on:
  pull_request:
    branches: [master]
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: read
  pull-requests: read

jobs:
  submission:
    name: Automated submission checks
    uses: web-programming-contest/web-programming-ci-utils/.github/workflows/submission.yml@2e9da3920f715ac25eb26d829c25574bcbf6c6f0
    with:
      utils_repository: web-programming-contest/web-programming-ci-utils
      utils_ref: "2e9da3920f715ac25eb26d829c25574bcbf6c6f0"
