name: Submission

on:
  pull_request:
    branches: [master]
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: read
  pull-requests: read

jobs:
  submission:
    name: Automated submission checks
    uses: web-programming-contest/web-programming-ci-utils/.github/workflows/submission.yml@df2e4096a7f45dd0a3598978a7c6b25aae9b6599
    with:
      utils_repository: web-programming-contest/web-programming-ci-utils
      utils_ref: "df2e4096a7f45dd0a3598978a7c6b25aae9b6599"
